import { getSessionParams, httpClient } from "@/services/core/client";
import { buildPaginatedParams } from "@/utils/api";
import type { Hotspot } from "../types/riskmaps.types";

export const REGION_1_HOTSPOTS: Hotspot[] = [
  // La Union (Vector, Waterborne, Respiratory, Environmental)
  {
    id: "lu-sfc-sevilla",
    muni: "Brgy. Sevilla, San Fernando City",
    barangay: "Sevilla",
    municipality: "San Fernando City",
    province: "La Union",
    disease: "dengue",
    diseaseName: "Dengue Fever",
    level: "high",
    lat: 16.6159,
    lng: 120.3209,
    cases: 48,
    probability: 0.82,
    sentinelFacility: "Bethany Hospital / CHO San Fernando",
  },
  {
    id: "lu-sfc-catbangen",
    muni: "Brgy. Catbangen, San Fernando City",
    barangay: "Catbangen",
    municipality: "San Fernando City",
    province: "La Union",
    disease: "dengue",
    diseaseName: "Dengue Fever",
    level: "high",
    lat: 16.6080,
    lng: 120.3170,
    cases: 42,
    probability: 0.76,
    sentinelFacility: "Ilocos Training and Regional Medical Center (ITRMC)",
  },
  {
    id: "lu-sfc-lingsat",
    muni: "Brgy. Lingsat, San Fernando City",
    barangay: "Lingsat",
    municipality: "San Fernando City",
    province: "La Union",
    disease: "ili",
    diseaseName: "Flu-like Illness (ILI)",
    level: "medium",
    lat: 16.6380,
    lng: 120.3270,
    cases: 38,
    probability: 0.54,
    sentinelFacility: "San Fernando City Health Station 2",
  },
  {
    id: "lu-agoo-san-nicolas",
    muni: "Brgy. San Nicolas, Agoo",
    barangay: "San Nicolas",
    municipality: "Agoo",
    province: "La Union",
    disease: "leptospirosis",
    diseaseName: "Leptospirosis",
    level: "high",
    lat: 16.3217,
    lng: 120.3647,
    cases: 24,
    probability: 0.79,
    sentinelFacility: "La Union Medical Center (LUMC)",
  },
  {
    id: "lu-agoo-sta-barbara",
    muni: "Brgy. Santa Barbara, Agoo",
    barangay: "Santa Barbara",
    municipality: "Agoo",
    province: "La Union",
    disease: "leptospirosis",
    diseaseName: "Leptospirosis",
    level: "medium",
    lat: 16.3150,
    lng: 120.3580,
    cases: 16,
    probability: 0.48,
    sentinelFacility: "Agoo RHU 1",
  },
  {
    id: "lu-bauang-central-east",
    muni: "Brgy. Central East, Bauang",
    barangay: "Central East",
    municipality: "Bauang",
    province: "La Union",
    disease: "dengue",
    diseaseName: "Dengue Fever",
    level: "medium",
    lat: 16.5244,
    lng: 120.3314,
    cases: 32,
    probability: 0.58,
    sentinelFacility: "Bauang RHU / Municipal Health Center",
  },
  {
    id: "lu-bauang-parian-oeste",
    muni: "Brgy. Parian Oeste, Bauang",
    barangay: "Parian Oeste",
    municipality: "Bauang",
    province: "La Union",
    disease: "asthma",
    diseaseName: "Bronchial Asthma Aggravation",
    level: "medium",
    lat: 16.5380,
    lng: 120.3220,
    cases: 20,
    probability: 0.45,
    sentinelFacility: "Bauang Rural Clinic",
  },
  {
    id: "lu-bacnotan-poblacion",
    muni: "Brgy. Poblacion, Bacnotan",
    barangay: "Poblacion",
    municipality: "Bacnotan",
    province: "La Union",
    disease: "ili",
    diseaseName: "Flu-like Illness (ILI)",
    level: "low",
    lat: 16.7210,
    lng: 120.3540,
    cases: 18,
    probability: 0.22,
    sentinelFacility: "Bacnotan District Hospital",
  },
  {
    id: "lu-naguilian-ortiz",
    muni: "Brgy. Ortiz, Naguilian",
    barangay: "Ortiz",
    municipality: "Naguilian",
    province: "La Union",
    disease: "dengue",
    diseaseName: "Dengue Fever",
    level: "medium",
    lat: 16.5310,
    lng: 120.3950,
    cases: 26,
    probability: 0.51,
    sentinelFacility: "Naguilian District Hospital",
  },

  // Pangasinan (Dengue, Leptospirosis, ILI)
  {
    id: "pan-dagupan-lucao",
    muni: "Brgy. Lucao, Dagupan City",
    barangay: "Lucao",
    municipality: "Dagupan City",
    province: "Pangasinan",
    disease: "dengue",
    diseaseName: "Dengue Fever",
    level: "high",
    lat: 16.0350,
    lng: 120.3150,
    cases: 52,
    probability: 0.84,
    sentinelFacility: "Region 1 Medical Center (R1MC)",
  },
  {
    id: "pan-dagupan-pantal",
    muni: "Brgy. Pantal, Dagupan City",
    barangay: "Pantal",
    municipality: "Dagupan City",
    province: "Pangasinan",
    disease: "leptospirosis",
    diseaseName: "Leptospirosis",
    level: "high",
    lat: 16.0480,
    lng: 120.3400,
    cases: 28,
    probability: 0.81,
    sentinelFacility: "Dagupan City Health Office",
  },
  {
    id: "pan-san-fabian-poblacion",
    muni: "Brgy. Poblacion, San Fabian",
    barangay: "Poblacion",
    municipality: "San Fabian",
    province: "Pangasinan",
    disease: "ili",
    diseaseName: "Flu-like Illness (ILI)",
    level: "low",
    lat: 16.1210,
    lng: 120.4020,
    cases: 22,
    probability: 0.28,
    sentinelFacility: "San Fabian RHU",
  },
  {
    id: "pan-lingayen-poblacion",
    muni: "Brgy. Poblacion, Lingayen",
    barangay: "Poblacion",
    municipality: "Lingayen",
    province: "Pangasinan",
    disease: "leptospirosis",
    diseaseName: "Leptospirosis",
    level: "medium",
    lat: 16.0222,
    lng: 120.2319,
    cases: 19,
    probability: 0.52,
    sentinelFacility: "Lingayen District Hospital",
  },

  // Ilocos Sur (Dengue, Asthma)
  {
    id: "is-vigan-pantay-daya",
    muni: "Brgy. Pantay Daya, Vigan City",
    barangay: "Pantay Daya",
    municipality: "Vigan City",
    province: "Ilocos Sur",
    disease: "dengue",
    diseaseName: "Dengue Fever",
    level: "medium",
    lat: 17.5680,
    lng: 120.3820,
    cases: 36,
    probability: 0.62,
    sentinelFacility: "Gabriela Silang General Hospital",
  },
  {
    id: "is-candon-san-nicolas",
    muni: "Brgy. San Nicolas, Candon City",
    barangay: "San Nicolas",
    municipality: "Candon City",
    province: "Ilocos Sur",
    disease: "asthma",
    diseaseName: "Bronchial Asthma Aggravation",
    level: "medium",
    lat: 17.1920,
    lng: 120.4480,
    cases: 19,
    probability: 0.44,
    sentinelFacility: "Candon General Hospital",
  },

  // Ilocos Norte (ILI, Asthma)
  {
    id: "in-laoag-san-guillermo",
    muni: "Brgy. San Guillermo, Laoag City",
    barangay: "San Guillermo",
    municipality: "Laoag City",
    province: "Ilocos Norte",
    disease: "ili",
    diseaseName: "Flu-like Illness (ILI)",
    level: "low",
    lat: 18.1960,
    lng: 120.5927,
    cases: 20,
    probability: 0.25,
    sentinelFacility: "Gov. Roque B. Ablan Sr. Memorial Hospital",
  },
  {
    id: "in-laoag-nalbo",
    muni: "Brgy. Nalbo, Laoag City",
    barangay: "Nalbo",
    municipality: "Laoag City",
    province: "Ilocos Norte",
    disease: "asthma",
    diseaseName: "Bronchial Asthma Aggravation",
    level: "low",
    lat: 18.1880,
    lng: 120.5840,
    cases: 15,
    probability: 0.28,
    sentinelFacility: "Laoag City Health Office",
  },
];

export async function listHotspots(): Promise<Hotspot[]> {
  try {
    const res = await httpClient<Hotspot[]>("/riskmaps/hotspots", {
      params: { ...getSessionParams(), ...buildPaginatedParams({}) },
    });
    if (res.data && res.data.length > 0) {
      return res.data;
    }
    return REGION_1_HOTSPOTS;
  } catch {
    return REGION_1_HOTSPOTS;
  }
}
